# Clarinet configuration for SafeTraffic-Ledger
# Maps local/testnet networks and project contracts for deployment

name = "SafeTraffic-Ledger"

[networks.local]
# Local Clarinet/Regtest node
url = "http://127.0.0.1:20443"

[networks.testnet]
# Stacks testnet (public API) — used for non-local deploys
url = "https://stacks-testnet-api.blockstack.org"

# Contract mappings: key = deployed contract name, value = path to .clar file
[contracts]
incident-registry = "Back/Contracts/incident_registry.clar"
