[project]
name = 'SafeTraffic-Ledger'
epoch = '2.4' 
clarity-version = 2

[contracts]
# ¡CAMBIO AQUÍ! Usa 'Contracts' con 'C' mayúscula
incident_registry = { path = "Contracts/incident_registry.clar" } 

[repl]
enable_trace_strings = true
pass_by-value = true