[project]
name = "incident-registry"
authors = ["Mateo Vargas, David Zema, Fabio Garcia Mesa"]
description = "Registro de incidentes en blockchain con Clarity"
telemetry = true
cache_dir = "./.cache"

# Si tu contrato depende de otros (por ejemplo traits u otros contratos en mainnet/testnet), añádelos aquí
# [[project.requirements]]
# contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[contracts.incident-registry]
path = "contracts/incident_registry.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
