[project]
name = "incident-registry-project"
authors = ["SafeTraffic Ledger"]
description = "Gestiona el registro inmutable y transparente de incidentes viales (multas, accidentes) mediante el modelo Commit-Reveal en Stacks."
telemetry = true
cache_dir = "./.cache"

# Tu contrato no parece tener requisitos de otros contratos (traits o implementaciones externas)
# por lo que esta sección se omite. Si más adelante añades un trait, deberás incluirlo aquí.
# [[project.requirements]]
# contract_id = "..." 

[contracts.incident-registry]
path = "SafeTraffic-Ledger\Back\Contracts\incident_registry.clar"
clarity_version = 2 # Asumiendo Clarity 2, ya que Clarity 3 aún no es el estándar común.
epoch = 2.4 # Estableciendo una epoch compatible con Clarity 2.

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false