[project]
name = 'SafeTraffic-Ledger'
epoch = '2.4' 
clarity-version = 2

[contracts]
incident_registry = { path = "contracts/incident_registry.clar" }

[repl]
enable_trace_strings = true
pass_by_value = true