[project]
name = 'SafeTraffic-Ledger'
epoch = '2.4' 
clarity-version = 2

[contracts]
# La C MAYÚSCULA es crucial aquí para que la plataforma web lo encuentre.
incident_registry = { path = "Contracts/incident_registry.clar" } 

[repl]
enable_trace_strings = true
pass_by_value = true